baseURL = 'https://www.strata.properties/blog/'
languageCode = 'en-us'
title = 'Strata Properties Blog'

[params]
  tagline = 'The daily frustrations of a Strata Owner in NSW Australia, and the fight to build a solution.'
