# Generated by Django 6.0.4 on 2026-04-22 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tenure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("owner", "Owner"), ("tenant", "Tenant")],
                        max_length=20,
                    ),
                ),
                ("from_date", models.DateField()),
                ("to_date", models.DateField(blank=True, null=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenures",
                        to="tracker.contact",
                    ),
                ),
                (
                    "parcel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenures",
                        to="tracker.parcel",
                    ),
                ),
            ],
        ),
    ]
