# Generated by Django 6.0.4 on 2026-04-22 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_issue"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("phone_call", "Phone Call"),
                            ("email", "Email"),
                            ("meeting", "Meeting"),
                            ("conversation", "Conversation"),
                            ("notice", "Notice"),
                            ("work", "Work"),
                            ("observation", "Observation"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cancelled", models.BooleanField(default=False)),
                ("date", models.DateTimeField()),
                ("duration", models.DurationField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="tracker.building",
                    ),
                ),
                (
                    "contacts",
                    models.ManyToManyField(
                        blank=True, related_name="events", to="tracker.contact"
                    ),
                ),
                (
                    "issues",
                    models.ManyToManyField(
                        blank=True, related_name="events", to="tracker.issue"
                    ),
                ),
                (
                    "parcels",
                    models.ManyToManyField(
                        blank=True, related_name="events", to="tracker.parcel"
                    ),
                ),
                (
                    "rescheduled_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rescheduled_to",
                        to="tracker.event",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
